spring:
  application:
    name: facility-discovery-service
  datasource:
    url: jdbc:postgresql://localhost:5432/pitchplease
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
  security:
    basic:
      enabled: false   

server:
  port: 0 

# # Customize application settings
# pitchplease:
#   app:
#     jwtSecret: pitchpleaseSecretKey
#     jwtExpirationMs: 86400000
